<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-IU1EAT0" failures="0" tests="1" name="TEST_CASES66.HYBEXCEL_Nation" time="18.826" errors="1" timestamp="2023-07-13T22:30:27 GMT-07:00" skipped="0">
  <testcase classname="TEST_CASES66.HYBEXCEL_Nation" name="M1" time="18.826">
    <error message="Fail to save: an error occurs while saving the package : null" type="org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException">
      <![CDATA[org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : null
at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:595)
at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1539)
at org.apache.poi.POIXMLDocument.write(POIXMLDocument.java:227)
at Reporter_Example_Word.ImageAttachmentInDocument1.WordOutput_File(ImageAttachmentInDocument1.java:114)
at TEST_CASES66.HYBEXCEL_Nation.M1(HYBEXCEL_Nation.java:86)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
at java.base/java.util.zip.DeflaterOutputStream.<init>(DeflaterOutputStream.java:83)
at java.base/java.util.zip.DeflaterOutputStream.<init>(DeflaterOutputStream.java:141)
at java.base/java.util.zip.ZipOutputStream.<init>(ZipOutputStream.java:133)
at java.base/java.util.zip.ZipOutputStream.<init>(ZipOutputStream.java:119)
at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:529)
... 29 more
]]>
    </error>
  </testcase> <!-- M1 -->
</testsuite> <!-- TEST_CASES66.HYBEXCEL_Nation -->
